/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VenuesRouteImport } from './routes/venues'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MessagesIndexRouteImport } from './routes/messages.index'
import { Route as ProfileExpertRouteImport } from './routes/profile.expert'
import { Route as ProfilIdRouteImport } from './routes/profil.$id'
import { Route as PodcastsIdRouteImport } from './routes/podcasts.$id'
import { Route as MessagesRequestIdRouteImport } from './routes/messages.$requestId'
import { Route as LieuxIdRouteImport } from './routes/lieux.$id'
import { Route as DashboardPodcasterRouteImport } from './routes/dashboard.podcaster'
import { Route as DashboardGuestRouteImport } from './routes/dashboard.guest'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthLoginRouteImport } from './routes/auth.login'

const VenuesRoute = VenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileExpertRoute = ProfileExpertRouteImport.update({
  id: '/profile/expert',
  path: '/profile/expert',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilIdRoute = ProfilIdRouteImport.update({
  id: '/profil/$id',
  path: '/profil/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastsIdRoute = PodcastsIdRouteImport.update({
  id: '/podcasts/$id',
  path: '/podcasts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRequestIdRoute = MessagesRequestIdRouteImport.update({
  id: '/messages/$requestId',
  path: '/messages/$requestId',
  getParentRoute: () => rootRouteImport,
} as any)
const LieuxIdRoute = LieuxIdRouteImport.update({
  id: '/lieux/$id',
  path: '/lieux/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPodcasterRoute = DashboardPodcasterRouteImport.update({
  id: '/dashboard/podcaster',
  path: '/dashboard/podcaster',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGuestRoute = DashboardGuestRouteImport.update({
  id: '/dashboard/guest',
  path: '/dashboard/guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/venues': typeof VenuesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/guest': typeof DashboardGuestRoute
  '/dashboard/podcaster': typeof DashboardPodcasterRoute
  '/lieux/$id': typeof LieuxIdRoute
  '/messages/$requestId': typeof MessagesRequestIdRoute
  '/podcasts/$id': typeof PodcastsIdRoute
  '/profil/$id': typeof ProfilIdRoute
  '/profile/expert': typeof ProfileExpertRoute
  '/messages/': typeof MessagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/venues': typeof VenuesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/guest': typeof DashboardGuestRoute
  '/dashboard/podcaster': typeof DashboardPodcasterRoute
  '/lieux/$id': typeof LieuxIdRoute
  '/messages/$requestId': typeof MessagesRequestIdRoute
  '/podcasts/$id': typeof PodcastsIdRoute
  '/profil/$id': typeof ProfilIdRoute
  '/profile/expert': typeof ProfileExpertRoute
  '/messages': typeof MessagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/venues': typeof VenuesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/guest': typeof DashboardGuestRoute
  '/dashboard/podcaster': typeof DashboardPodcasterRoute
  '/lieux/$id': typeof LieuxIdRoute
  '/messages/$requestId': typeof MessagesRequestIdRoute
  '/podcasts/$id': typeof PodcastsIdRoute
  '/profil/$id': typeof ProfilIdRoute
  '/profile/expert': typeof ProfileExpertRoute
  '/messages/': typeof MessagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/contact'
    | '/explore'
    | '/faq'
    | '/privacy'
    | '/terms'
    | '/venues'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/guest'
    | '/dashboard/podcaster'
    | '/lieux/$id'
    | '/messages/$requestId'
    | '/podcasts/$id'
    | '/profil/$id'
    | '/profile/expert'
    | '/messages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/contact'
    | '/explore'
    | '/faq'
    | '/privacy'
    | '/terms'
    | '/venues'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/guest'
    | '/dashboard/podcaster'
    | '/lieux/$id'
    | '/messages/$requestId'
    | '/podcasts/$id'
    | '/profil/$id'
    | '/profile/expert'
    | '/messages'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/contact'
    | '/explore'
    | '/faq'
    | '/privacy'
    | '/terms'
    | '/venues'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/guest'
    | '/dashboard/podcaster'
    | '/lieux/$id'
    | '/messages/$requestId'
    | '/podcasts/$id'
    | '/profil/$id'
    | '/profile/expert'
    | '/messages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  ExploreRoute: typeof ExploreRoute
  FaqRoute: typeof FaqRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  VenuesRoute: typeof VenuesRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  DashboardGuestRoute: typeof DashboardGuestRoute
  DashboardPodcasterRoute: typeof DashboardPodcasterRoute
  LieuxIdRoute: typeof LieuxIdRoute
  MessagesRequestIdRoute: typeof MessagesRequestIdRoute
  PodcastsIdRoute: typeof PodcastsIdRoute
  ProfilIdRoute: typeof ProfilIdRoute
  ProfileExpertRoute: typeof ProfileExpertRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/venues': {
      id: '/venues'
      path: '/venues'
      fullPath: '/venues'
      preLoaderRoute: typeof VenuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/expert': {
      id: '/profile/expert'
      path: '/profile/expert'
      fullPath: '/profile/expert'
      preLoaderRoute: typeof ProfileExpertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/$id': {
      id: '/profil/$id'
      path: '/profil/$id'
      fullPath: '/profil/$id'
      preLoaderRoute: typeof ProfilIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcasts/$id': {
      id: '/podcasts/$id'
      path: '/podcasts/$id'
      fullPath: '/podcasts/$id'
      preLoaderRoute: typeof PodcastsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$requestId': {
      id: '/messages/$requestId'
      path: '/messages/$requestId'
      fullPath: '/messages/$requestId'
      preLoaderRoute: typeof MessagesRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lieux/$id': {
      id: '/lieux/$id'
      path: '/lieux/$id'
      fullPath: '/lieux/$id'
      preLoaderRoute: typeof LieuxIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/podcaster': {
      id: '/dashboard/podcaster'
      path: '/dashboard/podcaster'
      fullPath: '/dashboard/podcaster'
      preLoaderRoute: typeof DashboardPodcasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/guest': {
      id: '/dashboard/guest'
      path: '/dashboard/guest'
      fullPath: '/dashboard/guest'
      preLoaderRoute: typeof DashboardGuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  ExploreRoute: ExploreRoute,
  FaqRoute: FaqRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  VenuesRoute: VenuesRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  DashboardGuestRoute: DashboardGuestRoute,
  DashboardPodcasterRoute: DashboardPodcasterRoute,
  LieuxIdRoute: LieuxIdRoute,
  MessagesRequestIdRoute: MessagesRequestIdRoute,
  PodcastsIdRoute: PodcastsIdRoute,
  ProfilIdRoute: ProfilIdRoute,
  ProfileExpertRoute: ProfileExpertRoute,
  MessagesIndexRoute: MessagesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
